version: '3'
services:
  sample-app:
    image: thanhlq/fastify-starter-kit
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_NAME=app_db
      - DB_USER=sa
      - DB_PASSWORD=sa214
    env_file:
      - .env
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - /opt/data/mysql8:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: sa214
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: sa214
    network_mode: "dev-net-214"
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    restart: always
    network_mode: "dev-net-214"
    ports:
      - 8089:8080
networks:
  default:
    external:
      name: dev-net-214
