openapi: 3.0.3
info:
  description: default service.
  version: 1.0.0
  title: API SYSTEM SERVICES
servers:
  - url: http://localhost
    description: Staging server
paths:
  /users:
    post:
      tags:
        - User
      summary: Register user
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerUser'
      responses:
        '200':
          $ref: '#/components/responses/handleHeaderAccept'
    get:
      security:
        - bearerAuth: []
      tags:
        - User
      summary: Get user by ids
      operationId: getUserByIds
      parameters:
        - in: query
          name: ids
          required: true
          description: 25,50,100
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/handleHeaderAccept'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Only Enter Token
    time-zone:
      type: apiKey
      in: header
      name: time-zone
      description: 'http://worldtimeapi.org/timezones, example: Asia/Ho_Chi_Minh'
  responses:
    handleHeaderAccept:
      description: abc
      content:
        application/json:
          schema: {}
  schemas:
    registerUser:
      type: object
      properties:
        email:
          type: string
          example: hai.tran@gmail.com
      xml:
        name: RegisterUser
