openapi: 3.0.3
info:
  title: API SYSTEM SERVICES
  description: "TBD"
  version: 1.0.0
servers:
  - url: http://localhost:3003
    description: Staging server
paths:
  #For User paths:
  /api/v1/users:
    $ref: ./v1/user/user.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, for documentation purposes only
      description: "Only Enter Token"
    time-zone:
      type: apiKey
      in: header
      name: time-zone
      description: 'http://worldtimeapi.org/timezones, example: Asia/Ho_Chi_Minh'
